== Overview
Stereo and mono LV2 plugins, four-band parametric equalisers.
Each section has an active/bypass switch, frequency, bandwidth and
gain controls. There is also a global bypass switch and gain control.

== DSP
The 2nd order resonant filters are implemented using a Mitra-Regalia
style lattice filter, which has the nice property of being stable
even while parameters are being changed.

All switches and controls are internally smoothed, so they can be
used 'live' whithout any clicks or zipper noises. This should make
this plugin a good candidate for use in systems that allow automation
of plugin control ports, such as Ardour, or for stage use.

The DSP code is written by Fons Adriaensen

== GUI
The GUI provides knobs and toggle buttons for tweaking filter
parameters. It also provides frequency response widget with
differently coloured curve for each section and separate curve for
total equalization effect.

The GUI uses the External UI extension. lv2rack (part of zynjacku)
supports this extension. Ardour-2.8 needs patch to support the
external UI extension.
